# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
        prometheus:
            image: prom/prometheus
            ports:
                - 9090:9090
            options: >-
                -v ${{ github.workspace }}/.github/prometheus.yml:/etc/prometheus/prometheus.yml

        grafana:
            image: grafana/grafana
            ports:
                - 3000:3000
            options: >-
                --health-cmd "curl --fail http://localhost:3000/api/health || exit 1"
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v4      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
